### ISSUE TITLE
generate.py fails to build

### ISSUE THREAD

**Issue by nolash** [WebAssembly/design#1176]
```
$ python2 tools/generate.py --dir . --out html/
Found 25 markdown sources:
Traceback (most recent call last):
  File "tools/generate.py", line 162, in <module>
    generated = pool.map(generate_html, sources)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
OSError: [Errno 2] No such file or directory
```

Commit 6bf6fa02 using `Python 2.7.14` on  `4.14.15-1-ARCH`

**Comment by jfbastien** [comment]
Hasn't been maintained in 3 years, so I deleted it.
